publisher: "Electric Book Works"
publisher-url: "http://electricbookworks.com"
name: "EBW training"
description: "Training materials in digital publishing"

url: http://localhost:4000
baseurl: /ebw-training

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments